#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="galaordering")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertCustomer(Customer instance);
  partial void UpdateCustomer(Customer instance);
  partial void DeleteCustomer(Customer instance);
  partial void InsertItemCategory(ItemCategory instance);
  partial void UpdateItemCategory(ItemCategory instance);
  partial void DeleteItemCategory(ItemCategory instance);
  partial void InsertItemType(ItemType instance);
  partial void UpdateItemType(ItemType instance);
  partial void DeleteItemType(ItemType instance);
  partial void InsertItemUOM(ItemUOM instance);
  partial void UpdateItemUOM(ItemUOM instance);
  partial void DeleteItemUOM(ItemUOM instance);
  partial void InsertReseller(Reseller instance);
  partial void UpdateReseller(Reseller instance);
  partial void DeleteReseller(Reseller instance);
  partial void InsertItem(Item instance);
  partial void UpdateItem(Item instance);
  partial void DeleteItem(Item instance);
  partial void InsertNumberRunNO(NumberRunNO instance);
  partial void UpdateNumberRunNO(NumberRunNO instance);
  partial void DeleteNumberRunNO(NumberRunNO instance);
  partial void InsertOrderDtl(OrderDtl instance);
  partial void UpdateOrderDtl(OrderDtl instance);
  partial void DeleteOrderDtl(OrderDtl instance);
  partial void InsertOrderHdr(OrderHdr instance);
  partial void UpdateOrderHdr(OrderHdr instance);
  partial void DeleteOrderHdr(OrderHdr instance);
  partial void InsertUserAcct(UserAcct instance);
  partial void UpdateUserAcct(UserAcct instance);
  partial void DeleteUserAcct(UserAcct instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Customer> Customers
	{
		get
		{
			return this.GetTable<Customer>();
		}
	}
	
	public System.Data.Linq.Table<ItemCategory> ItemCategories
	{
		get
		{
			return this.GetTable<ItemCategory>();
		}
	}
	
	public System.Data.Linq.Table<ItemType> ItemTypes
	{
		get
		{
			return this.GetTable<ItemType>();
		}
	}
	
	public System.Data.Linq.Table<ItemUOM> ItemUOMs
	{
		get
		{
			return this.GetTable<ItemUOM>();
		}
	}
	
	public System.Data.Linq.Table<Reseller> Resellers
	{
		get
		{
			return this.GetTable<Reseller>();
		}
	}
	
	public System.Data.Linq.Table<Item> Items
	{
		get
		{
			return this.GetTable<Item>();
		}
	}
	
	public System.Data.Linq.Table<NumberRunNO> NumberRunNOs
	{
		get
		{
			return this.GetTable<NumberRunNO>();
		}
	}
	
	public System.Data.Linq.Table<OrderDtl> OrderDtls
	{
		get
		{
			return this.GetTable<OrderDtl>();
		}
	}
	
	public System.Data.Linq.Table<OrderHdr> OrderHdrs
	{
		get
		{
			return this.GetTable<OrderHdr>();
		}
	}
	
	public System.Data.Linq.Table<UserAcct> UserAccts
	{
		get
		{
			return this.GetTable<UserAcct>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private System.Nullable<int> _ckey;
	
	private string _CustomerCode;
	
	private string _CustomerName;
	
	private string _Reseller;
	
	private string _Status;
	
	private string _Remarks;
	
	private System.Nullable<System.DateTime> _UpdateDate;
	
	private string _UpdateBy;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private string _CreateBy;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnckeyChanging(System.Nullable<int> value);
    partial void OnckeyChanged();
    partial void OnCustomerCodeChanging(string value);
    partial void OnCustomerCodeChanged();
    partial void OnCustomerNameChanging(string value);
    partial void OnCustomerNameChanged();
    partial void OnResellerChanging(string value);
    partial void OnResellerChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnUpdateByChanging(string value);
    partial void OnUpdateByChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    #endregion
	
	public Customer()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ckey", DbType="Int")]
	public System.Nullable<int> ckey
	{
		get
		{
			return this._ckey;
		}
		set
		{
			if ((this._ckey != value))
			{
				this.OnckeyChanging(value);
				this.SendPropertyChanging();
				this._ckey = value;
				this.SendPropertyChanged("ckey");
				this.OnckeyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerCode", DbType="NVarChar(20)")]
	public string CustomerCode
	{
		get
		{
			return this._CustomerCode;
		}
		set
		{
			if ((this._CustomerCode != value))
			{
				this.OnCustomerCodeChanging(value);
				this.SendPropertyChanging();
				this._CustomerCode = value;
				this.SendPropertyChanged("CustomerCode");
				this.OnCustomerCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="NVarChar(100)")]
	public string CustomerName
	{
		get
		{
			return this._CustomerName;
		}
		set
		{
			if ((this._CustomerName != value))
			{
				this.OnCustomerNameChanging(value);
				this.SendPropertyChanging();
				this._CustomerName = value;
				this.SendPropertyChanged("CustomerName");
				this.OnCustomerNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reseller", DbType="NVarChar(20)")]
	public string Reseller
	{
		get
		{
			return this._Reseller;
		}
		set
		{
			if ((this._Reseller != value))
			{
				this.OnResellerChanging(value);
				this.SendPropertyChanging();
				this._Reseller = value;
				this.SendPropertyChanged("Reseller");
				this.OnResellerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(20)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(500)")]
	public string Remarks
	{
		get
		{
			return this._Remarks;
		}
		set
		{
			if ((this._Remarks != value))
			{
				this.OnRemarksChanging(value);
				this.SendPropertyChanging();
				this._Remarks = value;
				this.SendPropertyChanged("Remarks");
				this.OnRemarksChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateDate
	{
		get
		{
			return this._UpdateDate;
		}
		set
		{
			if ((this._UpdateDate != value))
			{
				this.OnUpdateDateChanging(value);
				this.SendPropertyChanging();
				this._UpdateDate = value;
				this.SendPropertyChanged("UpdateDate");
				this.OnUpdateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(20)")]
	public string UpdateBy
	{
		get
		{
			return this._UpdateBy;
		}
		set
		{
			if ((this._UpdateBy != value))
			{
				this.OnUpdateByChanging(value);
				this.SendPropertyChanging();
				this._UpdateBy = value;
				this.SendPropertyChanged("UpdateBy");
				this.OnUpdateByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(20)")]
	public string CreateBy
	{
		get
		{
			return this._CreateBy;
		}
		set
		{
			if ((this._CreateBy != value))
			{
				this.OnCreateByChanging(value);
				this.SendPropertyChanging();
				this._CreateBy = value;
				this.SendPropertyChanged("CreateBy");
				this.OnCreateByChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ItemCategory")]
public partial class ItemCategory : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Code;
	
	private string _Description;
	
	private System.Nullable<System.DateTime> _UpdateDate;
	
	private string _UpdateBy;
	
	private string _CreateBy;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnUpdateByChanging(string value);
    partial void OnUpdateByChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    #endregion
	
	public ItemCategory()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Code
	{
		get
		{
			return this._Code;
		}
		set
		{
			if ((this._Code != value))
			{
				this.OnCodeChanging(value);
				this.SendPropertyChanging();
				this._Code = value;
				this.SendPropertyChanged("Code");
				this.OnCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(100)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateDate
	{
		get
		{
			return this._UpdateDate;
		}
		set
		{
			if ((this._UpdateDate != value))
			{
				this.OnUpdateDateChanging(value);
				this.SendPropertyChanging();
				this._UpdateDate = value;
				this.SendPropertyChanged("UpdateDate");
				this.OnUpdateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(20)")]
	public string UpdateBy
	{
		get
		{
			return this._UpdateBy;
		}
		set
		{
			if ((this._UpdateBy != value))
			{
				this.OnUpdateByChanging(value);
				this.SendPropertyChanging();
				this._UpdateBy = value;
				this.SendPropertyChanged("UpdateBy");
				this.OnUpdateByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(20)")]
	public string CreateBy
	{
		get
		{
			return this._CreateBy;
		}
		set
		{
			if ((this._CreateBy != value))
			{
				this.OnCreateByChanging(value);
				this.SendPropertyChanging();
				this._CreateBy = value;
				this.SendPropertyChanged("CreateBy");
				this.OnCreateByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ItemType")]
public partial class ItemType : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Code;
	
	private string _Description;
	
	private System.Nullable<System.DateTime> _UpdateDate;
	
	private string _UpdateBy;
	
	private string _CreateBy;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnUpdateByChanging(string value);
    partial void OnUpdateByChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    #endregion
	
	public ItemType()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Code
	{
		get
		{
			return this._Code;
		}
		set
		{
			if ((this._Code != value))
			{
				this.OnCodeChanging(value);
				this.SendPropertyChanging();
				this._Code = value;
				this.SendPropertyChanged("Code");
				this.OnCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(100)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateDate
	{
		get
		{
			return this._UpdateDate;
		}
		set
		{
			if ((this._UpdateDate != value))
			{
				this.OnUpdateDateChanging(value);
				this.SendPropertyChanging();
				this._UpdateDate = value;
				this.SendPropertyChanged("UpdateDate");
				this.OnUpdateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(20)")]
	public string UpdateBy
	{
		get
		{
			return this._UpdateBy;
		}
		set
		{
			if ((this._UpdateBy != value))
			{
				this.OnUpdateByChanging(value);
				this.SendPropertyChanging();
				this._UpdateBy = value;
				this.SendPropertyChanged("UpdateBy");
				this.OnUpdateByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(20)")]
	public string CreateBy
	{
		get
		{
			return this._CreateBy;
		}
		set
		{
			if ((this._CreateBy != value))
			{
				this.OnCreateByChanging(value);
				this.SendPropertyChanging();
				this._CreateBy = value;
				this.SendPropertyChanged("CreateBy");
				this.OnCreateByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ItemUOM")]
public partial class ItemUOM : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Code;
	
	private string _Description;
	
	private System.Nullable<System.DateTime> _UpdateDate;
	
	private string _UpdateBy;
	
	private string _CreateBy;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnUpdateByChanging(string value);
    partial void OnUpdateByChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    #endregion
	
	public ItemUOM()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Code
	{
		get
		{
			return this._Code;
		}
		set
		{
			if ((this._Code != value))
			{
				this.OnCodeChanging(value);
				this.SendPropertyChanging();
				this._Code = value;
				this.SendPropertyChanged("Code");
				this.OnCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(100)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateDate
	{
		get
		{
			return this._UpdateDate;
		}
		set
		{
			if ((this._UpdateDate != value))
			{
				this.OnUpdateDateChanging(value);
				this.SendPropertyChanging();
				this._UpdateDate = value;
				this.SendPropertyChanged("UpdateDate");
				this.OnUpdateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(20)")]
	public string UpdateBy
	{
		get
		{
			return this._UpdateBy;
		}
		set
		{
			if ((this._UpdateBy != value))
			{
				this.OnUpdateByChanging(value);
				this.SendPropertyChanging();
				this._UpdateBy = value;
				this.SendPropertyChanged("UpdateBy");
				this.OnUpdateByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(20)")]
	public string CreateBy
	{
		get
		{
			return this._CreateBy;
		}
		set
		{
			if ((this._CreateBy != value))
			{
				this.OnCreateByChanging(value);
				this.SendPropertyChanging();
				this._CreateBy = value;
				this.SendPropertyChanged("CreateBy");
				this.OnCreateByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reseller")]
public partial class Reseller : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private System.Nullable<int> _ckey;
	
	private string _ResellerCode;
	
	private string _ResellerName;
	
	private System.Nullable<System.DateTime> _UpdateDate;
	
	private string _UpdateBy;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private string _CreateBy;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnckeyChanging(System.Nullable<int> value);
    partial void OnckeyChanged();
    partial void OnResellerCodeChanging(string value);
    partial void OnResellerCodeChanged();
    partial void OnResellerNameChanging(string value);
    partial void OnResellerNameChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnUpdateByChanging(string value);
    partial void OnUpdateByChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    #endregion
	
	public Reseller()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ckey", DbType="Int")]
	public System.Nullable<int> ckey
	{
		get
		{
			return this._ckey;
		}
		set
		{
			if ((this._ckey != value))
			{
				this.OnckeyChanging(value);
				this.SendPropertyChanging();
				this._ckey = value;
				this.SendPropertyChanged("ckey");
				this.OnckeyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResellerCode", DbType="NVarChar(20)")]
	public string ResellerCode
	{
		get
		{
			return this._ResellerCode;
		}
		set
		{
			if ((this._ResellerCode != value))
			{
				this.OnResellerCodeChanging(value);
				this.SendPropertyChanging();
				this._ResellerCode = value;
				this.SendPropertyChanged("ResellerCode");
				this.OnResellerCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResellerName", DbType="NVarChar(50)")]
	public string ResellerName
	{
		get
		{
			return this._ResellerName;
		}
		set
		{
			if ((this._ResellerName != value))
			{
				this.OnResellerNameChanging(value);
				this.SendPropertyChanging();
				this._ResellerName = value;
				this.SendPropertyChanged("ResellerName");
				this.OnResellerNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateDate
	{
		get
		{
			return this._UpdateDate;
		}
		set
		{
			if ((this._UpdateDate != value))
			{
				this.OnUpdateDateChanging(value);
				this.SendPropertyChanging();
				this._UpdateDate = value;
				this.SendPropertyChanged("UpdateDate");
				this.OnUpdateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(20)")]
	public string UpdateBy
	{
		get
		{
			return this._UpdateBy;
		}
		set
		{
			if ((this._UpdateBy != value))
			{
				this.OnUpdateByChanging(value);
				this.SendPropertyChanging();
				this._UpdateBy = value;
				this.SendPropertyChanged("UpdateBy");
				this.OnUpdateByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(20)")]
	public string CreateBy
	{
		get
		{
			return this._CreateBy;
		}
		set
		{
			if ((this._CreateBy != value))
			{
				this.OnCreateByChanging(value);
				this.SendPropertyChanging();
				this._CreateBy = value;
				this.SendPropertyChanged("CreateBy");
				this.OnCreateByChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Item")]
public partial class Item : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private System.Nullable<int> _ckey;
	
	private string _ItemCode;
	
	private string _ItemName;
	
	private string _ItemNameCN;
	
	private string _ItemType;
	
	private string _ItemCategory;
	
	private string _ItemUom;
	
	private string _ItemStatus;
	
	private string _ProcessItemCode;
	
	private System.Nullable<System.DateTime> _UpdateDate;
	
	private string _UpdateBy;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private string _CreateBy;
	
	private System.Nullable<bool> _isProcessItem;
	
	private string _imageUrl;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnckeyChanging(System.Nullable<int> value);
    partial void OnckeyChanged();
    partial void OnItemCodeChanging(string value);
    partial void OnItemCodeChanged();
    partial void OnItemNameChanging(string value);
    partial void OnItemNameChanged();
    partial void OnItemNameCNChanging(string value);
    partial void OnItemNameCNChanged();
    partial void OnItemTypeChanging(string value);
    partial void OnItemTypeChanged();
    partial void OnItemCategoryChanging(string value);
    partial void OnItemCategoryChanged();
    partial void OnItemUomChanging(string value);
    partial void OnItemUomChanged();
    partial void OnItemStatusChanging(string value);
    partial void OnItemStatusChanged();
    partial void OnProcessItemCodeChanging(string value);
    partial void OnProcessItemCodeChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnUpdateByChanging(string value);
    partial void OnUpdateByChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    partial void OnisProcessItemChanging(System.Nullable<bool> value);
    partial void OnisProcessItemChanged();
    partial void OnimageUrlChanging(string value);
    partial void OnimageUrlChanged();
    #endregion
	
	public Item()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ckey", DbType="Int")]
	public System.Nullable<int> ckey
	{
		get
		{
			return this._ckey;
		}
		set
		{
			if ((this._ckey != value))
			{
				this.OnckeyChanging(value);
				this.SendPropertyChanging();
				this._ckey = value;
				this.SendPropertyChanged("ckey");
				this.OnckeyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCode", DbType="NVarChar(50)")]
	public string ItemCode
	{
		get
		{
			return this._ItemCode;
		}
		set
		{
			if ((this._ItemCode != value))
			{
				this.OnItemCodeChanging(value);
				this.SendPropertyChanging();
				this._ItemCode = value;
				this.SendPropertyChanged("ItemCode");
				this.OnItemCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemName", DbType="NVarChar(200)")]
	public string ItemName
	{
		get
		{
			return this._ItemName;
		}
		set
		{
			if ((this._ItemName != value))
			{
				this.OnItemNameChanging(value);
				this.SendPropertyChanging();
				this._ItemName = value;
				this.SendPropertyChanged("ItemName");
				this.OnItemNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemNameCN", DbType="NVarChar(400)")]
	public string ItemNameCN
	{
		get
		{
			return this._ItemNameCN;
		}
		set
		{
			if ((this._ItemNameCN != value))
			{
				this.OnItemNameCNChanging(value);
				this.SendPropertyChanging();
				this._ItemNameCN = value;
				this.SendPropertyChanged("ItemNameCN");
				this.OnItemNameCNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemType", DbType="NVarChar(50)")]
	public string ItemType
	{
		get
		{
			return this._ItemType;
		}
		set
		{
			if ((this._ItemType != value))
			{
				this.OnItemTypeChanging(value);
				this.SendPropertyChanging();
				this._ItemType = value;
				this.SendPropertyChanged("ItemType");
				this.OnItemTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCategory", DbType="NVarChar(50)")]
	public string ItemCategory
	{
		get
		{
			return this._ItemCategory;
		}
		set
		{
			if ((this._ItemCategory != value))
			{
				this.OnItemCategoryChanging(value);
				this.SendPropertyChanging();
				this._ItemCategory = value;
				this.SendPropertyChanged("ItemCategory");
				this.OnItemCategoryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemUom", DbType="NVarChar(20)")]
	public string ItemUom
	{
		get
		{
			return this._ItemUom;
		}
		set
		{
			if ((this._ItemUom != value))
			{
				this.OnItemUomChanging(value);
				this.SendPropertyChanging();
				this._ItemUom = value;
				this.SendPropertyChanged("ItemUom");
				this.OnItemUomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemStatus", DbType="NVarChar(20)")]
	public string ItemStatus
	{
		get
		{
			return this._ItemStatus;
		}
		set
		{
			if ((this._ItemStatus != value))
			{
				this.OnItemStatusChanging(value);
				this.SendPropertyChanging();
				this._ItemStatus = value;
				this.SendPropertyChanged("ItemStatus");
				this.OnItemStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessItemCode", DbType="NVarChar(20)")]
	public string ProcessItemCode
	{
		get
		{
			return this._ProcessItemCode;
		}
		set
		{
			if ((this._ProcessItemCode != value))
			{
				this.OnProcessItemCodeChanging(value);
				this.SendPropertyChanging();
				this._ProcessItemCode = value;
				this.SendPropertyChanged("ProcessItemCode");
				this.OnProcessItemCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateDate
	{
		get
		{
			return this._UpdateDate;
		}
		set
		{
			if ((this._UpdateDate != value))
			{
				this.OnUpdateDateChanging(value);
				this.SendPropertyChanging();
				this._UpdateDate = value;
				this.SendPropertyChanged("UpdateDate");
				this.OnUpdateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(20)")]
	public string UpdateBy
	{
		get
		{
			return this._UpdateBy;
		}
		set
		{
			if ((this._UpdateBy != value))
			{
				this.OnUpdateByChanging(value);
				this.SendPropertyChanging();
				this._UpdateBy = value;
				this.SendPropertyChanged("UpdateBy");
				this.OnUpdateByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(20)")]
	public string CreateBy
	{
		get
		{
			return this._CreateBy;
		}
		set
		{
			if ((this._CreateBy != value))
			{
				this.OnCreateByChanging(value);
				this.SendPropertyChanging();
				this._CreateBy = value;
				this.SendPropertyChanged("CreateBy");
				this.OnCreateByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isProcessItem", DbType="Bit")]
	public System.Nullable<bool> isProcessItem
	{
		get
		{
			return this._isProcessItem;
		}
		set
		{
			if ((this._isProcessItem != value))
			{
				this.OnisProcessItemChanging(value);
				this.SendPropertyChanging();
				this._isProcessItem = value;
				this.SendPropertyChanged("isProcessItem");
				this.OnisProcessItemChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageUrl", DbType="NVarChar(150)")]
	public string imageUrl
	{
		get
		{
			return this._imageUrl;
		}
		set
		{
			if ((this._imageUrl != value))
			{
				this.OnimageUrlChanging(value);
				this.SendPropertyChanging();
				this._imageUrl = value;
				this.SendPropertyChanged("imageUrl");
				this.OnimageUrlChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NumberRunNO")]
public partial class NumberRunNO : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private short _Year;
	
	private System.Nullable<short> _Month;
	
	private string _NumCd;
	
	private string _NumDes;
	
	private System.Nullable<short> _TotLength;
	
	private string _Prefix;
	
	private System.Nullable<long> _Seq;
	
	private System.Nullable<System.DateTime> _Created;
	
	private System.Nullable<System.DateTime> _Updated;
	
	private string _UserID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnYearChanging(short value);
    partial void OnYearChanged();
    partial void OnMonthChanging(System.Nullable<short> value);
    partial void OnMonthChanged();
    partial void OnNumCdChanging(string value);
    partial void OnNumCdChanged();
    partial void OnNumDesChanging(string value);
    partial void OnNumDesChanged();
    partial void OnTotLengthChanging(System.Nullable<short> value);
    partial void OnTotLengthChanged();
    partial void OnPrefixChanging(string value);
    partial void OnPrefixChanged();
    partial void OnSeqChanging(System.Nullable<long> value);
    partial void OnSeqChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    #endregion
	
	public NumberRunNO()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="SmallInt NOT NULL")]
	public short Year
	{
		get
		{
			return this._Year;
		}
		set
		{
			if ((this._Year != value))
			{
				this.OnYearChanging(value);
				this.SendPropertyChanging();
				this._Year = value;
				this.SendPropertyChanged("Year");
				this.OnYearChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="SmallInt")]
	public System.Nullable<short> Month
	{
		get
		{
			return this._Month;
		}
		set
		{
			if ((this._Month != value))
			{
				this.OnMonthChanging(value);
				this.SendPropertyChanging();
				this._Month = value;
				this.SendPropertyChanged("Month");
				this.OnMonthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumCd", DbType="NVarChar(20)")]
	public string NumCd
	{
		get
		{
			return this._NumCd;
		}
		set
		{
			if ((this._NumCd != value))
			{
				this.OnNumCdChanging(value);
				this.SendPropertyChanging();
				this._NumCd = value;
				this.SendPropertyChanged("NumCd");
				this.OnNumCdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumDes", DbType="NVarChar(30)")]
	public string NumDes
	{
		get
		{
			return this._NumDes;
		}
		set
		{
			if ((this._NumDes != value))
			{
				this.OnNumDesChanging(value);
				this.SendPropertyChanging();
				this._NumDes = value;
				this.SendPropertyChanged("NumDes");
				this.OnNumDesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotLength", DbType="SmallInt")]
	public System.Nullable<short> TotLength
	{
		get
		{
			return this._TotLength;
		}
		set
		{
			if ((this._TotLength != value))
			{
				this.OnTotLengthChanging(value);
				this.SendPropertyChanging();
				this._TotLength = value;
				this.SendPropertyChanged("TotLength");
				this.OnTotLengthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prefix", DbType="NVarChar(20)")]
	public string Prefix
	{
		get
		{
			return this._Prefix;
		}
		set
		{
			if ((this._Prefix != value))
			{
				this.OnPrefixChanging(value);
				this.SendPropertyChanging();
				this._Prefix = value;
				this.SendPropertyChanged("Prefix");
				this.OnPrefixChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seq", DbType="BigInt")]
	public System.Nullable<long> Seq
	{
		get
		{
			return this._Seq;
		}
		set
		{
			if ((this._Seq != value))
			{
				this.OnSeqChanging(value);
				this.SendPropertyChanging();
				this._Seq = value;
				this.SendPropertyChanged("Seq");
				this.OnSeqChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
	public System.Nullable<System.DateTime> Created
	{
		get
		{
			return this._Created;
		}
		set
		{
			if ((this._Created != value))
			{
				this.OnCreatedChanging(value);
				this.SendPropertyChanging();
				this._Created = value;
				this.SendPropertyChanged("Created");
				this.OnCreatedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="DateTime")]
	public System.Nullable<System.DateTime> Updated
	{
		get
		{
			return this._Updated;
		}
		set
		{
			if ((this._Updated != value))
			{
				this.OnUpdatedChanging(value);
				this.SendPropertyChanging();
				this._Updated = value;
				this.SendPropertyChanged("Updated");
				this.OnUpdatedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(10)")]
	public string UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this.OnUserIDChanging(value);
				this.SendPropertyChanging();
				this._UserID = value;
				this.SendPropertyChanged("UserID");
				this.OnUserIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderDtl")]
public partial class OrderDtl : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private System.Nullable<int> _ckey;
	
	private string _OrderNo;
	
	private System.Nullable<int> _OrderLine;
	
	private System.Nullable<int> _Line;
	
	private string _ItemCode;
	
	private string _ItemUom;
	
	private string _ItemName;
	
	private System.Nullable<decimal> _Quantity;
	
	private string _Remark;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnckeyChanging(System.Nullable<int> value);
    partial void OnckeyChanged();
    partial void OnOrderNoChanging(string value);
    partial void OnOrderNoChanged();
    partial void OnOrderLineChanging(System.Nullable<int> value);
    partial void OnOrderLineChanged();
    partial void OnLineChanging(System.Nullable<int> value);
    partial void OnLineChanged();
    partial void OnItemCodeChanging(string value);
    partial void OnItemCodeChanged();
    partial void OnItemUomChanging(string value);
    partial void OnItemUomChanged();
    partial void OnItemNameChanging(string value);
    partial void OnItemNameChanged();
    partial void OnQuantityChanging(System.Nullable<decimal> value);
    partial void OnQuantityChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
	
	public OrderDtl()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ckey", DbType="Int")]
	public System.Nullable<int> ckey
	{
		get
		{
			return this._ckey;
		}
		set
		{
			if ((this._ckey != value))
			{
				this.OnckeyChanging(value);
				this.SendPropertyChanging();
				this._ckey = value;
				this.SendPropertyChanged("ckey");
				this.OnckeyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNo", DbType="NVarChar(20)")]
	public string OrderNo
	{
		get
		{
			return this._OrderNo;
		}
		set
		{
			if ((this._OrderNo != value))
			{
				this.OnOrderNoChanging(value);
				this.SendPropertyChanging();
				this._OrderNo = value;
				this.SendPropertyChanged("OrderNo");
				this.OnOrderNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderLine", DbType="Int")]
	public System.Nullable<int> OrderLine
	{
		get
		{
			return this._OrderLine;
		}
		set
		{
			if ((this._OrderLine != value))
			{
				this.OnOrderLineChanging(value);
				this.SendPropertyChanging();
				this._OrderLine = value;
				this.SendPropertyChanged("OrderLine");
				this.OnOrderLineChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Line", DbType="Int")]
	public System.Nullable<int> Line
	{
		get
		{
			return this._Line;
		}
		set
		{
			if ((this._Line != value))
			{
				this.OnLineChanging(value);
				this.SendPropertyChanging();
				this._Line = value;
				this.SendPropertyChanged("Line");
				this.OnLineChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCode", DbType="NVarChar(50)")]
	public string ItemCode
	{
		get
		{
			return this._ItemCode;
		}
		set
		{
			if ((this._ItemCode != value))
			{
				this.OnItemCodeChanging(value);
				this.SendPropertyChanging();
				this._ItemCode = value;
				this.SendPropertyChanged("ItemCode");
				this.OnItemCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemUom", DbType="NVarChar(20)")]
	public string ItemUom
	{
		get
		{
			return this._ItemUom;
		}
		set
		{
			if ((this._ItemUom != value))
			{
				this.OnItemUomChanging(value);
				this.SendPropertyChanging();
				this._ItemUom = value;
				this.SendPropertyChanged("ItemUom");
				this.OnItemUomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemName", DbType="NVarChar(200)")]
	public string ItemName
	{
		get
		{
			return this._ItemName;
		}
		set
		{
			if ((this._ItemName != value))
			{
				this.OnItemNameChanging(value);
				this.SendPropertyChanging();
				this._ItemName = value;
				this.SendPropertyChanged("ItemName");
				this.OnItemNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> Quantity
	{
		get
		{
			return this._Quantity;
		}
		set
		{
			if ((this._Quantity != value))
			{
				this.OnQuantityChanging(value);
				this.SendPropertyChanging();
				this._Quantity = value;
				this.SendPropertyChanged("Quantity");
				this.OnQuantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(200)")]
	public string Remark
	{
		get
		{
			return this._Remark;
		}
		set
		{
			if ((this._Remark != value))
			{
				this.OnRemarkChanging(value);
				this.SendPropertyChanging();
				this._Remark = value;
				this.SendPropertyChanged("Remark");
				this.OnRemarkChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderHdr")]
public partial class OrderHdr : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private System.Nullable<int> _ckey;
	
	private string _OrderNo;
	
	private string _OrderStatus;
	
	private System.Nullable<System.DateTime> _OrderDate;
	
	private string _CustomerCode;
	
	private string _CustomerName;
	
	private string _ResellerCode;
	
	private string _AccountStatus;
	
	private string _OrderType;
	
	private string _Remark;
	
	private System.Nullable<System.DateTime> _UpdateDate;
	
	private string _UpdateBy;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private string _CreateBy;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnckeyChanging(System.Nullable<int> value);
    partial void OnckeyChanged();
    partial void OnOrderNoChanging(string value);
    partial void OnOrderNoChanged();
    partial void OnOrderStatusChanging(string value);
    partial void OnOrderStatusChanged();
    partial void OnOrderDateChanging(System.Nullable<System.DateTime> value);
    partial void OnOrderDateChanged();
    partial void OnCustomerCodeChanging(string value);
    partial void OnCustomerCodeChanged();
    partial void OnCustomerNameChanging(string value);
    partial void OnCustomerNameChanged();
    partial void OnResellerCodeChanging(string value);
    partial void OnResellerCodeChanged();
    partial void OnAccountStatusChanging(string value);
    partial void OnAccountStatusChanged();
    partial void OnOrderTypeChanging(string value);
    partial void OnOrderTypeChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnUpdateByChanging(string value);
    partial void OnUpdateByChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    #endregion
	
	public OrderHdr()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ckey", DbType="Int")]
	public System.Nullable<int> ckey
	{
		get
		{
			return this._ckey;
		}
		set
		{
			if ((this._ckey != value))
			{
				this.OnckeyChanging(value);
				this.SendPropertyChanging();
				this._ckey = value;
				this.SendPropertyChanged("ckey");
				this.OnckeyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNo", DbType="NVarChar(20)")]
	public string OrderNo
	{
		get
		{
			return this._OrderNo;
		}
		set
		{
			if ((this._OrderNo != value))
			{
				this.OnOrderNoChanging(value);
				this.SendPropertyChanging();
				this._OrderNo = value;
				this.SendPropertyChanged("OrderNo");
				this.OnOrderNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderStatus", DbType="NVarChar(10)")]
	public string OrderStatus
	{
		get
		{
			return this._OrderStatus;
		}
		set
		{
			if ((this._OrderStatus != value))
			{
				this.OnOrderStatusChanging(value);
				this.SendPropertyChanging();
				this._OrderStatus = value;
				this.SendPropertyChanged("OrderStatus");
				this.OnOrderStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> OrderDate
	{
		get
		{
			return this._OrderDate;
		}
		set
		{
			if ((this._OrderDate != value))
			{
				this.OnOrderDateChanging(value);
				this.SendPropertyChanging();
				this._OrderDate = value;
				this.SendPropertyChanged("OrderDate");
				this.OnOrderDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerCode", DbType="NVarChar(20)")]
	public string CustomerCode
	{
		get
		{
			return this._CustomerCode;
		}
		set
		{
			if ((this._CustomerCode != value))
			{
				this.OnCustomerCodeChanging(value);
				this.SendPropertyChanging();
				this._CustomerCode = value;
				this.SendPropertyChanged("CustomerCode");
				this.OnCustomerCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="NVarChar(100)")]
	public string CustomerName
	{
		get
		{
			return this._CustomerName;
		}
		set
		{
			if ((this._CustomerName != value))
			{
				this.OnCustomerNameChanging(value);
				this.SendPropertyChanging();
				this._CustomerName = value;
				this.SendPropertyChanged("CustomerName");
				this.OnCustomerNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResellerCode", DbType="NVarChar(20)")]
	public string ResellerCode
	{
		get
		{
			return this._ResellerCode;
		}
		set
		{
			if ((this._ResellerCode != value))
			{
				this.OnResellerCodeChanging(value);
				this.SendPropertyChanging();
				this._ResellerCode = value;
				this.SendPropertyChanged("ResellerCode");
				this.OnResellerCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountStatus", DbType="NVarChar(10)")]
	public string AccountStatus
	{
		get
		{
			return this._AccountStatus;
		}
		set
		{
			if ((this._AccountStatus != value))
			{
				this.OnAccountStatusChanging(value);
				this.SendPropertyChanging();
				this._AccountStatus = value;
				this.SendPropertyChanged("AccountStatus");
				this.OnAccountStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderType", DbType="NVarChar(20)")]
	public string OrderType
	{
		get
		{
			return this._OrderType;
		}
		set
		{
			if ((this._OrderType != value))
			{
				this.OnOrderTypeChanging(value);
				this.SendPropertyChanging();
				this._OrderType = value;
				this.SendPropertyChanged("OrderType");
				this.OnOrderTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(200)")]
	public string Remark
	{
		get
		{
			return this._Remark;
		}
		set
		{
			if ((this._Remark != value))
			{
				this.OnRemarkChanging(value);
				this.SendPropertyChanging();
				this._Remark = value;
				this.SendPropertyChanged("Remark");
				this.OnRemarkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateDate
	{
		get
		{
			return this._UpdateDate;
		}
		set
		{
			if ((this._UpdateDate != value))
			{
				this.OnUpdateDateChanging(value);
				this.SendPropertyChanging();
				this._UpdateDate = value;
				this.SendPropertyChanged("UpdateDate");
				this.OnUpdateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(20)")]
	public string UpdateBy
	{
		get
		{
			return this._UpdateBy;
		}
		set
		{
			if ((this._UpdateBy != value))
			{
				this.OnUpdateByChanging(value);
				this.SendPropertyChanging();
				this._UpdateBy = value;
				this.SendPropertyChanged("UpdateBy");
				this.OnUpdateByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(20)")]
	public string CreateBy
	{
		get
		{
			return this._CreateBy;
		}
		set
		{
			if ((this._CreateBy != value))
			{
				this.OnCreateByChanging(value);
				this.SendPropertyChanging();
				this._CreateBy = value;
				this.SendPropertyChanged("CreateBy");
				this.OnCreateByChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserAcct")]
public partial class UserAcct : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _ID;
	
	private string _Name;
	
	private string _PWord;
	
	private string _Status;
	
	private System.Nullable<System.DateTime> _UpdateDate;
	
	private string _UpdateBy;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private string _CreateBy;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPWordChanging(string value);
    partial void OnPWordChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnUpdateByChanging(string value);
    partial void OnUpdateByChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    #endregion
	
	public UserAcct()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(30)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PWord", DbType="NVarChar(40)")]
	public string PWord
	{
		get
		{
			return this._PWord;
		}
		set
		{
			if ((this._PWord != value))
			{
				this.OnPWordChanging(value);
				this.SendPropertyChanging();
				this._PWord = value;
				this.SendPropertyChanged("PWord");
				this.OnPWordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(20)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateDate
	{
		get
		{
			return this._UpdateDate;
		}
		set
		{
			if ((this._UpdateDate != value))
			{
				this.OnUpdateDateChanging(value);
				this.SendPropertyChanging();
				this._UpdateDate = value;
				this.SendPropertyChanged("UpdateDate");
				this.OnUpdateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(20)")]
	public string UpdateBy
	{
		get
		{
			return this._UpdateBy;
		}
		set
		{
			if ((this._UpdateBy != value))
			{
				this.OnUpdateByChanging(value);
				this.SendPropertyChanging();
				this._UpdateBy = value;
				this.SendPropertyChanged("UpdateBy");
				this.OnUpdateByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(20)")]
	public string CreateBy
	{
		get
		{
			return this._CreateBy;
		}
		set
		{
			if ((this._CreateBy != value))
			{
				this.OnCreateByChanging(value);
				this.SendPropertyChanging();
				this._CreateBy = value;
				this.SendPropertyChanged("CreateBy");
				this.OnCreateByChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
