<?xml version="1.0" encoding="utf-8"?><Database Name="galaordering" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MOK-HP;Initial Catalog=galaordering;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="galaorderingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ckey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Reseller" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ItemCategory" Member="ItemCategories">
    <Type Name="ItemCategory">
      <Column Name="Code" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ItemType" Member="ItemTypes">
    <Type Name="ItemType">
      <Column Name="Code" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ItemUOM" Member="ItemUOMs">
    <Type Name="ItemUOM">
      <Column Name="Code" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reseller" Member="Resellers">
    <Type Name="Reseller">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ckey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResellerCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ResellerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Item" Member="Items">
    <Type Name="Item">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ckey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ItemNameCN" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="ItemType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemCategory" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemUom" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ItemStatus" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ProcessItemCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="isProcessItem" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="imageUrl" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NumberRunNO" Member="NumberRunNOs">
    <Type Name="NumberRunNO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Year" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="NumCd" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NumDes" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TotLength" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Prefix" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Seq" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDtl" Member="OrderDtls">
    <Type Name="OrderDtl">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ckey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="OrderLine" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Line" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemUom" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderHdr" Member="OrderHdrs">
    <Type Name="OrderHdr">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ckey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="OrderStatus" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CustomerCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ResellerCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="AccountStatus" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="OrderType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserAcct" Member="UserAccts">
    <Type Name="UserAcct">
      <Column Name="ID" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PWord" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustAcct" Member="CustAccts">
    <Type Name="CustAcct">
      <Column Name="ID" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PWord" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CustomerCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="chgpass" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderSettings" Member="OrderSettings">
    <Type Name="OrderSetting">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="beforeOrdertime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="maxorderperday" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>